name: Laravel CI/CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. 檢查程式碼
      - uses: actions/checkout@v4

      # 2. 設置 PHP 環境
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Update Composer
        run: composer self-update
      # 3. 安裝 Composer 依賴
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      # 4. 複製環境檔案
      - name: Copy .env
        run: cp .env.example .env

      # 5. 生成應用程式金鑰
      - name: Generate Application Key
        run: php artisan key:generate

      # 6. 執行 Laravel Pint 檢查程式碼風格
      - name: Run Laravel Pint
        run: ./vendor/bin/pint --test

      # 7. 執行 PHPStan 靜態分析
      - name: Run PHPStan
        run: ./vendor/bin/phpstan analyse

      # 8. 執行測試
      - name: Run Tests
        run: php artisan test
